/**
 * 首次启动时把 CLI 装到 PATH 上，让用户装完 app 就有 `proxybaby` 命令可用。
 *
 * 打包后的 app 结构：
 *   /Applications/ProxyBaby.app/Contents/Resources/bin/proxybaby.cjs   ← electron-builder extraResources 拷进来
 *
 * 目标：
 *   1) /usr/local/bin/proxybaby → 一个包装脚本，转发到 Resources/bin/proxybaby.cjs
 *      （不直接 symlink 到 .app 里，避免 app 被移动时脚本失效；用脚本查找已注册的 app）
 *   2) 幂等：已经安装过就跳过；升级时脚本内容不同才更新
 *   3) 需要 sudo 时静默失败，UI 可以给一个"用管理员权限安装"按钮由用户手动触发
 *
 * 未打包（开发模式 electron .）时跳过。
 *
 * SKILL.md 不内置进 app —— 用户走 README 里的 "一句 prompt 让 AI 帮你装 skill"
 * （AI agent 自己从 https://github.com/imcuttle/proxybaby 拉 SKILL.md 到本地）。
 */
import fs from 'node:fs';
import fsp from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { app } from 'electron';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';

const execFileP = promisify(execFile);

const BIN_DIR_CANDIDATES = ['/usr/local/bin', '/opt/homebrew/bin'];
const LINK_NAME = 'proxybaby';

function cliScriptPath(): string {
  // extraResources 会把 bin/proxybaby.cjs 拷到 Resources/bin/proxybaby.cjs
  return path.join(process.resourcesPath, 'bin', 'proxybaby.cjs');
}

function wrapperContent(cliPath: string): string {
  return `#!/bin/sh
# ProxyBaby CLI wrapper — auto-generated by the ProxyBaby app.
# Do NOT edit; the app rewrites this file on next launch.
CLI_JS="${cliPath.replace(/"/g, '\\"')}"
if [ ! -f "$CLI_JS" ]; then
  echo "proxybaby: CLI script missing at $CLI_JS. Reinstall the app." >&2
  exit 1
fi
if command -v node >/dev/null 2>&1; then
  exec node "$CLI_JS" "$@"
fi
echo "proxybaby: 'node' not found in PATH. Install Node.js (18+) and re-run." >&2
exit 1
`;
}

async function isWritable(p: string): Promise<boolean> {
  try { await fsp.access(p, fs.constants.W_OK); return true; } catch { return false; }
}

async function pickBinDir(): Promise<string | null> {
  for (const d of BIN_DIR_CANDIDATES) {
    if (fs.existsSync(d) && (await isWritable(d))) return d;
  }
  return null;
}

export type CliInstallResult =
  | { ok: true; path: string; created: boolean; updated: boolean }
  | { ok: false; reason: string; needsSudo?: boolean };

/**
 * 幂等安装 CLI wrapper。ok=false 时通常需要用户提权。
 */
export async function installCliLink(opts: { force?: boolean } = {}): Promise<CliInstallResult> {
  if (!app.isPackaged) return { ok: false, reason: '开发模式（未打包），跳过 CLI 安装' };
  if (process.platform !== 'darwin') return { ok: false, reason: '仅支持 macOS' };

  const cliJs = cliScriptPath();
  if (!fs.existsSync(cliJs)) {
    return { ok: false, reason: `未找到 CLI 脚本: ${cliJs}` };
  }
  const desired = wrapperContent(cliJs);

  const binDir = await pickBinDir();
  if (!binDir) {
    return {
      ok: false,
      reason: `${BIN_DIR_CANDIDATES.join(' 或 ')} 均不可写，需要 sudo`,
      needsSudo: true,
    };
  }
  const target = path.join(binDir, LINK_NAME);

  let existing = '';
  try { existing = await fsp.readFile(target, 'utf8'); } catch { /* not exist */ }

  if (!opts.force && existing === desired) {
    return { ok: true, path: target, created: false, updated: false };
  }

  await fsp.writeFile(target, desired, { mode: 0o755 });
  return { ok: true, path: target, created: !existing, updated: !!existing };
}

/**
 * 如果 pickBinDir 都不可写，用户可以在 UI 里点"用管理员权限安装"——osascript 弹密码框。
 */
export async function installCliLinkWithSudo(): Promise<CliInstallResult> {
  if (!app.isPackaged) return { ok: false, reason: '开发模式（未打包）' };
  if (process.platform !== 'darwin') return { ok: false, reason: '仅支持 macOS' };

  const cliJs = cliScriptPath();
  if (!fs.existsSync(cliJs)) return { ok: false, reason: `未找到 CLI 脚本: ${cliJs}` };

  const target = '/usr/local/bin/' + LINK_NAME;
  const desired = wrapperContent(cliJs);
  const tmp = path.join(os.tmpdir(), `proxybaby-cli-${Date.now()}.sh`);
  await fsp.writeFile(tmp, desired, { mode: 0o755 });
  const cmd = `/bin/mkdir -p /usr/local/bin && /bin/mv "${tmp}" "${target}" && /bin/chmod 755 "${target}"`;
  const script = `do shell script "${cmd.replace(/"/g, '\\"')}" with administrator privileges`;
  try {
    await execFileP('osascript', ['-e', script]);
    return { ok: true, path: target, created: true, updated: false };
  } catch (err: any) {
    return { ok: false, reason: `osascript 提权失败: ${err.message || err}` };
  } finally {
    try { await fsp.unlink(tmp); } catch {}
  }
}
